### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by LostKobrakai** [jloh/geojs#38]
It seems geojs does currently not support IPv6. Is this something that could be added?

**Comment by jloh** [comment]
Hi @LostKobrakai! GeoJS does support IPv6 out of the box. Are you seeing otherwise?

If you could give me an example IP or something you're seeing it not return results for that'd be great!

**Comment by LostKobrakai** [comment]
I just saw that in the routes. It returns data for the IP of my server (the IPv6 I had at hand), but doesn't yield useful results with everything being nil or Unknown. I'll try a few other IPs.

**Comment by jloh** [comment]
It could be that the DBs GeoJS uses doesn't have information on the IP you're looking up, but it does work. For example https://get.geojs.io/v1/ip/geo/2001:4860:4860::8888.json

I can have a further look if you pass through an IP. If you don't want to post it publicly you can send it through to `contact @ geojs.io`

**Comment by LostKobrakai** [comment]
I've tried a few more public ones. I cannot seem to get timezone information for them, but at least lat/long and country code. Maybe the information is better for private ips than server type ones. This works for me for now, thanks.

**Comment by jloh** [comment]
IPv6 data can be a bit inaccurate given its still "new" so to speak and the address space is so large. Hopefully it'll get more accurate as time goes on!
