### ISSUE TITLE
List of countries with pretty names

### ISSUE THREAD

**Issue by derpekka** [jloh/geojs#39]
Hi Jloh, and thanks for building this! It really does make the forms on our website so much more user friendly.

For digital marketing purposes, we're looking for a list of all the pretty names that the country API returns. Do you know where could we find such a list?

**Comment by jloh** [comment]
Hi @derpekka, not quite sure what you mean sorry. Are you meaning the `name` value in the country endpoint?

[This list from Maxmind](https://dev.maxmind.com/geoip/legacy/codes/iso3166/) is probably the closest thing if thats what you mean!

**Comment by derpekka** [comment]
Yeah, I was talking about the name value, but we actually resolved the
issue by using the country codes instead. Thanks!
___________________________________________________

Pekka Hiltunen | Web team leader

Celonis SE | Theresienstrasse 6 | 80333 München Germany

p.hiltunen@celonis.com | www.celonis.com | LinkedIn | Twitter | Xing

AG Munich HRB 225439 | Management: Martin Klenk, Bastian Nominacher,
Alexander Rinke

This e-mail may contain trade secrets or privileged, undisclosed, or
otherwise confidential information. If you have received this e-mail in
error, you are hereby notified that any review, copying, or distribution of
it is strictly prohibited. Please inform us immediately and destroy the
original transmittal. Thank you for your cooperation.
