### ISSUE TITLE
[Bug] API returns wrong location

### ISSUE THREAD

**Issue by roy1210** [jloh/geojs#44]
Hi team!
This is such a great API! 
I am happy to use it :D

However, I found an error about fetching data from IP: 78.47.78.165. This IP should belong to "Germany", but the API returns "US"

https://app.geojs.io/s/78.47.78.165
https://ipgeolocation.io/browse/ip/78.47.78.165

Highly appreciate if you can fix this issue! Thank you!

**Comment by jloh** [comment]
Hi @roy1210. The data provided by GeoJS is supplied from the MaxMind GeoLite2 databases. Unfortunately these databases can sometimes be slower to update compared to paid services which can result in the responses you're seeing. They usually resolve after 1-2 months but its outside of my control.

Thanks for using GeoJS!
