### ISSUE TITLE
ipv6 endpoint is now unreachable

### ISSUE THREAD

**Issue by vnihoul77** [jloh/geojs#45]
It seems like this endpoint: **https://ipv6.geojs.io/v1/ip** is not working anymore?

Did something changed? If so how to just get the ipv6 version of the client'ip ?

**Comment by jloh** [comment]
@vnihoul77 its working for me. Can you let me know what IP it resolves to so I can investigate further?

**Comment by vnihoul77** [comment]
Thanks for checking.
This IP for instance is not working : 195.240.253.53
As well as other reported by my customers.

**Comment by jloh** [comment]
195.240.253.53 is not a GeoJS IP, I'm not sure what that IP is for. The IPv6 endpoint only works if you have IPv6 connectivity since there is now IPv4 record associated with it:

```
❯ dig ipv6.geojs.io

; <<>> DiG 9.10.6 <<>> ipv6.geojs.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 63485
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;ipv6.geojs.io.			IN	A

;; ANSWER SECTION:
ipv6.geojs.io.		300	IN	CNAME	ipv6.geojs-backend.com.

;; AUTHORITY SECTION:
geojs-backend.com.	900	IN	SOA	ns-1924.awsdns-48.co.uk. awsdns-hostmaster.amazon.com. 1 7200 900 1209600 86400

;; Query time: 358 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Mon May 31 13:04:40 AEST 2021
;; MSG SIZE  rcvd: 162
```

If you're able to go into more details on how it isn't working I can look further but everything is working fine on this end.
