### ISSUE TITLE
GeoIP down?

### ISSUE THREAD

**Issue by systemcrash** [jloh/geojs#46]
Weird, https://status.geojs.io/ says 100% up
but 
https://get.geojs.io/
https://www.geojs.io/docs/v1/endpoints/geo/
https://www.geojs.io/

etc are 100% down right now

I access it from Sweden, tried both v4/6

Probably because dig shows:
```
dig get.geojs.io @8.8.8.8

; <<>> DiG 9.10.6 <<>> get.geojs.io @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25799
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;get.geojs.io.			IN	A

;; ANSWER SECTION:
get.geojs.io.		2994	IN	A	0.0.0.0
```

Is this some kind of DoS protection? 😦 

Now status just went off-line.....

```
dig status.geojs.io @8.8.8.8

; <<>> DiG 9.10.6 <<>> status.geojs.io @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 17021
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;status.geojs.io.		IN	A

;; ANSWER SECTION:
status.geojs.io.	3435	IN	A	0.0.0.0

```

**Comment by laukstein** [comment]
It works for me.

**Comment by systemcrash** [comment]
> It works for me.

it?

**Comment by jloh** [comment]
Hey @systemcrash, no outages I'm able to see here. From the looks of it your DNS isn't resolving domains correctly. The geojs.io domain has DNSSEC applied to it so perhaps your resolver is struggling to verify that correctly.

If the issues keep coming back feel free to open this issue again.

**Comment by systemcrash** [comment]
OK - thanks for looking into it. Evidently Adguard took to blocking DNS lookups for your domain - possible association of this lookup mechanism with some privacy invasion. 

https://adguard.com/en/adguard-dns/overview.html
