### ISSUE TITLE
Blocked by ad blocking plugins

### ISSUE THREAD

**Issue by NoverNobida** [jloh/geojs#47]
Scripts are always blocked by ad blocking plugins. Whether to consider changing the name(https://get.geojs.io/v1/ip/geo.js), or users can self-hosted it?

**Comment by jloh** [comment]
Thanks for reaching out. I'm not going to try and work around adblockers since its a cat and mouse game and honestly I believe what they're doing is fair.

GeoJS doesn't have any logging and I believe I'm privacy respecting but I also respect the decision they've made.
